name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  universal_io: ^2.0.4
  provider: ^6.0.4
  flutter_file_downloader: ^2.0.0
  path_provider: ^2.0.15
  dio: ^4.0.0
  http: ^0.13.3
  http_parser: ^4.0.0
  file_picker: ^8.0.0+1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/input.png
    - assets/output.png